/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActivityAdd: typeof import('./resources/js/components/admin/timesheet/activity-add.vue')['default']
    ActivityEdit: typeof import('./resources/js/components/admin/timesheet/activity-edit.vue')['default']
    Additional_add: typeof import('./resources/js/components/admin/cut-off/additional_add.vue')['default']
    CancelRequest: typeof import('./resources/js/components/user/request/cancel-request.vue')['default']
    CardStatisticsHorizontal: typeof import('./resources/js/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./resources/js/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./resources/js/@core/components/cards/CardStatisticsWithImages.vue')['default']
    Cutoff_add: typeof import('./resources/js/components/admin/cut-off/cutoff_add.vue')['default']
    Cutoff_existing_add: typeof import('./resources/js/components/admin/cut-off/cutoff_existing_add.vue')['default']
    DeleteHandler: typeof import('./resources/js/components/DeleteHandler.vue')['default']
    ErrorHeader: typeof import('./resources/js/components/ErrorHeader.vue')['default']
    MoreBtn: typeof import('./resources/js/@core/components/MoreBtn.vue')['default']
    NewRequest: typeof import('./resources/js/components/user/request/new-request.vue')['default']
    Program_add: typeof import('./resources/js/components/admin/program/program_add.vue')['default']
    Program_add_specialist: typeof import('./resources/js/components/admin/program/program_add_specialist.vue')['default']
    Program_add_tutoring: typeof import('./resources/js/components/admin/program/program_add_tutoring.vue')['default']
    Qalendar: typeof import('./resources/js/components/Qalendar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Security: typeof import('./resources/js/components/user/setting/security.vue')['default']
    ThemeSwitcher: typeof import('./resources/js/@core/components/ThemeSwitcher.vue')['default']
    TimesheetDetail: typeof import('./resources/js/components/admin/timesheet/timesheet-detail.vue')['default']
    TimesheetTransfer: typeof import('./resources/js/components/admin/timesheet/timesheet-transfer.vue')['default']
    UpgradeToPro: typeof import('./resources/js/components/UpgradeToPro.vue')['default']
    UserDetail: typeof import('./resources/js/components/admin/timesheet/user-detail.vue')['default']
    UserEdit: typeof import('./resources/js/components/admin/timesheet/user-edit.vue')['default']
  }
}
